production:
  GOOGLE_OAUTH_KEY: 828204908476-r0dkfm27kr7sdf0cadht5c2lncghd159.apps.googleusercontent.com
  GOOGLE_OAUTH_SECRET: R-U-qazXG94-asTivCpfGwA3
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr
  GOOGLE_API_KEY: AIzaSyBq88AFCI5YwfIFPplkx7v4tiPPC0H_qJ8
  MANDRILL_API_KEY: c5F4ml-YZLDYG9Ibfn1V8A
  MANDRILL_USERNAME: alexandra.scott335@gmail.com
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr

development:
  GOOGLE_OAUTH_KEY: 828204908476-r0dkfm27kr7sdf0cadht5c2lncghd159.apps.googleusercontent.com
  GOOGLE_OAUTH_SECRET: R-U-qazXG94-asTivCpfGwA3
  GOOGLE_API_KEY: AIzaSyBq88AFCI5YwfIFPplkx7v4tiPPC0H_qJ8
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr
  MANDRILL_API_KEY: c5F4ml-YZLDYG9Ibfn1V8A
  MANDRILL_USERNAME: alexandra.scott335@gmail.com
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr

test:
  GOOGLE_OAUTH_KEY: 828204908476-r0dkfm27kr7sdf0cadht5c2lncghd159.apps.googleusercontent.com
  GOOGLE_OAUTH_SECRET: R-U-qazXG94-asTivCpfGwA3
  GOOGLE_API_KEY: AIzaSyBq88AFCI5YwfIFPplkx7v4tiPPC0H_qJ8
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr
  MANDRILL_API_KEY: c5F4ml-YZLDYG9Ibfn1V8A
  MANDRILL_USERNAME: alexandra.scott335@gmail.com
  EVENTFUL_API_KEY: DdBNfvmp5tfQ7zGr
